services:
  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file: 
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: app_db
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  backend:
    image: app_backend    
    build: ./backend
    entrypoint: ["/bin/sh", "entrypoint.sh"]
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./backend:/app/

volumes:
  pgdata: